/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package optimizadordemezclas;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Luigi
 */
public class Inicio extends javax.swing.JPanel {

    
    private String[] estado;
    private String path;
    private JLabel[] resultados;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        path = System.getProperty("user.dir");
        
        resultados = new JLabel[19];
        
        resultados[0] = txtNomBa1;
        resultados[1] = txBa1;
        resultados[2] = txCUBa1;
        resultados[3] = txCanBa1;
        resultados[4] = txCpBa1;
        resultados[5] = txtNomBa2;
        resultados[6] = txBa2;
        resultados[7] = txCUBa2;
        resultados[8] = txCanBa2;
        resultados[9] = txCpBa2;
        resultados[10] = txtNomBa3;
        resultados[11] = txBa3;
        resultados[12] = txCUBa3;
        resultados[13] = txCanBa3;
        resultados[14] = txCpBa3;
        resultados[15] = txtViscoCin;
        resultados[16] = txtViscoDin;
        resultados[17] = txtColor;
        resultados[18] = txtVola;
        
        
        
        ArrayList<String> itemsCombo = Utils.generaCol("formulaciones.csv", 3);
        Collections.sort(itemsCombo);
        
        for(String s : itemsCombo)
            combo.addItem(s);
        
        //Esconde label avio
        txAviso.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcula = new javax.swing.JButton();
        txCpM = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        txAviso = new javax.swing.JLabel();
        lbDemanda = new javax.swing.JLabel();
        txtDemanda = new javax.swing.JTextField();
        txtCodProd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txLinea = new javax.swing.JLabel();
        txB1n = new javax.swing.JLabel();
        txB1c = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txB1x = new javax.swing.JLabel();
        txCst = new javax.swing.JLabel();
        txTemp = new javax.swing.JLabel();
        txCp = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txGrado = new javax.swing.JLabel();
        txB2n = new javax.swing.JLabel();
        txB2c = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txB2x = new javax.swing.JLabel();
        txColor = new javax.swing.JLabel();
        txVol = new javax.swing.JLabel();
        txCpM1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txBa3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtInfoBas = new javax.swing.JLabel();
        txBa1 = new javax.swing.JLabel();
        txBa2 = new javax.swing.JLabel();
        txCUBa3 = new javax.swing.JLabel();
        txCUBa1 = new javax.swing.JLabel();
        txCUBa2 = new javax.swing.JLabel();
        txCanBa3 = new javax.swing.JLabel();
        txCanBa1 = new javax.swing.JLabel();
        txCanBa2 = new javax.swing.JLabel();
        txCpBa3 = new javax.swing.JLabel();
        txCpBa1 = new javax.swing.JLabel();
        txCpBa2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        txCostMez2 = new javax.swing.JLabel();
        txtValFin = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txCostMez1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtNomBa1 = new javax.swing.JLabel();
        txtNomBa2 = new javax.swing.JLabel();
        txtNomBa3 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtInfoBas1 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        txtViscoCin = new javax.swing.JLabel();
        txtViscoDin = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        txtVola = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setForeground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Código de producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 110, -1, -1));

        btnCalcula.setText("Calcular");
        btnCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        txCpM.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCpM.setForeground(new java.awt.Color(204, 204, 204));
        txCpM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimizadordemezclas/logo.png"))); // NOI18N
        jPanel1.add(txCpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboKeyPressed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        txAviso.setText("Calculando...");
        txAviso.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txAvisoComponentShown(evt);
            }
        });
        jPanel1.add(txAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 80, 20));

        lbDemanda.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbDemanda.setText("Ingrese la demanda");
        jPanel1.add(lbDemanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));
        jPanel1.add(txtDemanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 100, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 980));

        txtCodProd.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtCodProd.setForeground(new java.awt.Color(204, 204, 204));
        txtCodProd.setText("bla bla");
        add(txtCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Código del producto:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("CP sin mejorador:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 810, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Línea:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 560, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("B1 Composición:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("B1 Código:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, -1, -1));

        txLinea.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txLinea.setForeground(new java.awt.Color(204, 204, 204));
        txLinea.setText("bla bla");
        txLinea.setName("txLinea"); // NOI18N
        add(txLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, -1, -1));

        txB1n.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB1n.setForeground(new java.awt.Color(204, 204, 204));
        txB1n.setText("bla bla");
        add(txB1n, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, -1, -1));

        txB1c.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB1c.setForeground(new java.awt.Color(204, 204, 204));
        txB1c.setText("bla bla");
        add(txB1c, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 670, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("B1 X1:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 730, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("cSt a 100°C:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 810, -1, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Temp para CCS:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 730, -1, -1));

        txB1x.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB1x.setForeground(new java.awt.Color(204, 204, 204));
        txB1x.setText("bla bla");
        add(txB1x, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 760, -1, -1));

        txCst.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCst.setForeground(new java.awt.Color(204, 204, 204));
        txCst.setText("bla bla");
        add(txCst, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 840, -1, -1));

        txTemp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txTemp.setForeground(new java.awt.Color(204, 204, 204));
        txTemp.setText("bla bla");
        add(txTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 760, -1, -1));

        txCp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCp.setForeground(new java.awt.Color(204, 204, 204));
        txCp.setText("bla bla");
        add(txCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 840, -1, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("CP con mejorador:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 810, -1, -1));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Grado:");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 560, -1, -1));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("B2 Composición:");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 640, -1, -1));

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("B2 Código:");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 640, -1, -1));

        txGrado.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txGrado.setForeground(new java.awt.Color(204, 204, 204));
        txGrado.setText("bla bla");
        add(txGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 590, -1, -1));

        txB2n.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB2n.setForeground(new java.awt.Color(204, 204, 204));
        txB2n.setText("bla bla");
        add(txB2n, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 670, -1, -1));

        txB2c.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB2c.setForeground(new java.awt.Color(204, 204, 204));
        txB2c.setText("bla bla");
        add(txB2c, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 670, -1, -1));

        jLabel39.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("B2 X2:");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 730, -1, -1));

        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("Volatilidad");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 360, -1, -1));

        jLabel41.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("Volatilidad:");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 730, -1, -1));

        txB2x.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB2x.setForeground(new java.awt.Color(204, 204, 204));
        txB2x.setText("bla bla");
        add(txB2x, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 760, -1, -1));

        txColor.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txColor.setForeground(new java.awt.Color(204, 204, 204));
        txColor.setText("bla bla");
        add(txColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 840, -1, -1));

        txVol.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txVol.setForeground(new java.awt.Color(204, 204, 204));
        txVol.setText("bla bla");
        add(txVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 760, -1, -1));

        txCpM1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCpM1.setForeground(new java.awt.Color(204, 204, 204));
        txCpM1.setText("bla bla");
        add(txCpM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 840, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 1100, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 250, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 10, 60));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Formulación");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 250, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 10, 80));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Resultados");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        txBa3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txBa3.setForeground(new java.awt.Color(204, 204, 204));
        txBa3.setText("bla bla");
        add(txBa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Cantidad (kg)");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, -1, -1));

        txtInfoBas.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInfoBas.setForeground(new java.awt.Color(204, 204, 204));
        txtInfoBas.setText("Información de producto");
        add(txtInfoBas, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, -1, -1));

        txBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txBa1.setForeground(new java.awt.Color(204, 204, 204));
        txBa1.setText("bla bla");
        add(txBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, -1, -1));

        txBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txBa2.setForeground(new java.awt.Color(204, 204, 204));
        txBa2.setText("bla bla");
        add(txBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, -1, -1));

        txCUBa3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCUBa3.setForeground(new java.awt.Color(204, 204, 204));
        txCUBa3.setText("bla bla");
        add(txCUBa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, -1, -1));

        txCUBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCUBa1.setForeground(new java.awt.Color(204, 204, 204));
        txCUBa1.setText("bla bla");
        add(txCUBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 150, -1, -1));

        txCUBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCUBa2.setForeground(new java.awt.Color(204, 204, 204));
        txCUBa2.setText("bla bla");
        add(txCUBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, -1, -1));

        txCanBa3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCanBa3.setForeground(new java.awt.Color(204, 204, 204));
        txCanBa3.setText("bla bla");
        add(txCanBa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 250, -1, -1));

        txCanBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCanBa1.setForeground(new java.awt.Color(204, 204, 204));
        txCanBa1.setText("bla bla");
        add(txCanBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 150, -1, -1));

        txCanBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCanBa2.setForeground(new java.awt.Color(204, 204, 204));
        txCanBa2.setText("bla bla");
        add(txCanBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 200, -1, -1));

        txCpBa3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCpBa3.setForeground(new java.awt.Color(204, 204, 204));
        txCpBa3.setText("bla bla");
        add(txCpBa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 250, -1, -1));

        txCpBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCpBa1.setForeground(new java.awt.Color(204, 204, 204));
        txCpBa1.setText("bla bla");
        add(txCpBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 150, -1, -1));

        txCpBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCpBa2.setForeground(new java.awt.Color(204, 204, 204));
        txCpBa2.setText("bla bla");
        add(txCpBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 200, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 750, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 10, 60));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 10, 80));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, 10, 80));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 60, 10, 80));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 60, 10, 80));

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("El costo total de mezcla de básicos con la formulación optimizada es:");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea1.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 250, 70));

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Costo por      básico\n   (mxn)");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea2.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 60, 100, 80));

        txCostMez2.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        txCostMez2.setForeground(new java.awt.Color(204, 204, 204));
        txCostMez2.setText("bla bla");
        add(txCostMez2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        txtValFin.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        txtValFin.setForeground(new java.awt.Color(204, 204, 204));
        txtValFin.setText("bla bla");
        add(txtValFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Ahorro al optimizar:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        txCostMez1.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        txCostMez1.setForeground(new java.awt.Color(204, 204, 204));
        txCostMez1.setText("bla bla");
        add(txCostMez1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jScrollPane4.setBorder(null);
        jScrollPane4.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("El costo total de mezcla de básicos sin optimizar la formulación es:");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea4.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane4.setViewportView(jTextArea4);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 250, 70));

        jScrollPane3.setBorder(null);
        jScrollPane3.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText(" Viscosidad\n  dinámica \n       (cP)");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea3.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane3.setViewportView(jTextArea3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 130, 70));

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 330, 10, 80));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Básicos");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        txtNomBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNomBa1.setForeground(new java.awt.Color(204, 204, 204));
        txtNomBa1.setText("bla bla");
        add(txtNomBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        txtNomBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNomBa2.setForeground(new java.awt.Color(204, 204, 204));
        txtNomBa2.setText("bla bla");
        add(txtNomBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        txtNomBa3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNomBa3.setForeground(new java.awt.Color(204, 204, 204));
        txtNomBa3.setText("bla bla");
        add(txtNomBa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 750, 10));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Nombre de básico");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, -1));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 750, 10));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 750, 10));
        add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 750, 10));
        add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 750, 10));
        add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 750, 10));
        add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 750, 10));

        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 10, 80));

        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 330, 10, 80));

        jScrollPane5.setBorder(null);
        jScrollPane5.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("Costo unitario\n   (mxn/kg)");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea5.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane5.setViewportView(jTextArea5);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, 140, 70));

        jScrollPane6.setBorder(null);
        jScrollPane6.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setText(" Viscosidad\n cinemática\n(csT @ 100°C)");
        jTextArea6.setWrapStyleWord(true);
        jTextArea6.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea6.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane6.setViewportView(jTextArea6);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 130, 70));

        jLabel42.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("Color:");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 810, -1, -1));

        jLabel43.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("Color");
        add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 360, -1, -1));

        txtInfoBas1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInfoBas1.setForeground(new java.awt.Color(204, 204, 204));
        txtInfoBas1.setText("Información de básicos");
        add(txtInfoBas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, -1, -1));

        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 10, 80));

        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 10, 80));

        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 330, 10, 80));

        txtViscoCin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtViscoCin.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoCin.setText("bla bla");
        add(txtViscoCin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        txtViscoDin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtViscoDin.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoDin.setText("bla bla");
        add(txtViscoDin, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 440, -1, -1));

        txtColor.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtColor.setForeground(new java.awt.Color(204, 204, 204));
        txtColor.setText("bla bla");
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 440, -1, -1));

        txtVola.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtVola.setForeground(new java.awt.Color(204, 204, 204));
        txtVola.setText("bla bla");
        add(txtVola, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    static String readFile(String path, Charset encoding) throws IOException 
    {
        //System.out.println(path);
      byte[] encoded = Files.readAllBytes(Paths.get(path));
      return new String(encoded, encoding);
    }
    
    private void cargaEstado(){
       // System.out.println(path);
        try {
          String aux = readFile(path+"\\producto.txt",Charset.defaultCharset());
          estado = aux.split(";");
        }
        catch(IOException e){
            System.out.println("Error al leer archivo");
        }
        
    
    }
    private void btnCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaActionPerformed
        // TODO add your handling code here:
        System.out.println(combo.getSelectedItem());
        txAviso.setVisible(true);
        
        for(int i =0; i<resultados.length; i++){
            resultados[i].setText("");
        }
        
        txtCodProd.setText("");
        txLinea.setText("");
        txB1n.setText("");
        txB1c.setText("");
        txB1x.setText("");
        txCst.setText("");
        txTemp.setText("");
        txCp.setText("");   
        txGrado.setText("");
        txB2n.setText("");
        txB2c.setText("");
        txB2x.setText("");
        txColor.setText("");
        txVol.setText("");
        txCpM1.setText("");
        txCostMez1.setText("");
        txCostMez2.setText("");
        txtValFin.setText("");
        
    }//GEN-LAST:event_btnCalculaActionPerformed

    private void comboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txAviso.setVisible(true);
            System.out.println("set visible");
               // TODO add your handling code here:
        
        
        }
            
    }//GEN-LAST:event_comboKeyPressed

    private void txAvisoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txAvisoComponentShown
        // TODO add your handling code here:
        System.out.println(combo.getSelectedItem());
        try{ 
            Runtime rt = Runtime.getRuntime();
            System.out.println(path);
            Process pr = rt.exec("julia codPrueba.jl.txt "+combo.getSelectedItem() + " " +txtDemanda.getText());
//            //pr.waitFor();
//              ProcessBuilder builder = new ProcessBuilder("julia", "codPrueba.jl.txt" + inCodigoProd.getText());
//              builder.redirectErrorStream(true);
//              Process process;
                
//                process = builder.start();
                
               InputStream is = pr.getInputStream();
               String line;
               BufferedReader reader = new BufferedReader(new InputStreamReader(is));
               
               while((line = reader.readLine()) != null){
                   System.out.print(line);
               }



            cargaEstado();
            if(estado != null){
                txtCodProd.setText(estado[2]);
                txLinea.setText(estado[0]);
                txB1n.setText(estado[3]);
                txB1c.setText(estado[4]);
                txB1x.setText(estado[5]);
                txCst.setText(estado[9]);
                txTemp.setText(estado[10]);
                txCp.setText(estado[11]);   
                txGrado.setText(estado[1]);
                txB2n.setText(estado[6]);
                txB2c.setText(estado[7]);
                txB2x.setText(estado[8]);
                txColor.setText(estado[12]);
                txVol.setText(estado[13]);
                txCpM1.setText(estado[14]);

            }
            
            ArrayList<String> valsTab = Utils.generaDataCsv("tablaRes.txt");
        
            int i = 0;
            int lim = valsTab.size();
            
            while(i<lim){
                resultados[i].setText(valsTab.get(i));
                i++;
            }
            
            
            String[] vals = Utils.leeValRes("valoresRes.txt");
            
            
            txCostMez1.setText(vals[0].substring(1, vals[1].length()-1));
            txCostMez2.setText(vals[1]);
            
            double x1 = Double.parseDouble(vals[0].substring(1, vals[1].length()-1));
            double x2 = Double.parseDouble(vals[1]);
            double resp = x1-x2;
            
            txtValFin.setText(""+resp);
            
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        txAviso.setVisible(false);
    }//GEN-LAST:event_txAvisoComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcula;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JLabel lbDemanda;
    private javax.swing.JLabel txAviso;
    private javax.swing.JLabel txB1c;
    private javax.swing.JLabel txB1n;
    private javax.swing.JLabel txB1x;
    private javax.swing.JLabel txB2c;
    private javax.swing.JLabel txB2n;
    private javax.swing.JLabel txB2x;
    private javax.swing.JLabel txBa1;
    private javax.swing.JLabel txBa2;
    private javax.swing.JLabel txBa3;
    private javax.swing.JLabel txCUBa1;
    private javax.swing.JLabel txCUBa2;
    private javax.swing.JLabel txCUBa3;
    private javax.swing.JLabel txCanBa1;
    private javax.swing.JLabel txCanBa2;
    private javax.swing.JLabel txCanBa3;
    private javax.swing.JLabel txColor;
    private javax.swing.JLabel txCostMez1;
    private javax.swing.JLabel txCostMez2;
    private javax.swing.JLabel txCp;
    private javax.swing.JLabel txCpBa1;
    private javax.swing.JLabel txCpBa2;
    private javax.swing.JLabel txCpBa3;
    private javax.swing.JLabel txCpM;
    private javax.swing.JLabel txCpM1;
    private javax.swing.JLabel txCst;
    private javax.swing.JLabel txGrado;
    private javax.swing.JLabel txLinea;
    private javax.swing.JLabel txTemp;
    private javax.swing.JLabel txVol;
    private javax.swing.JLabel txtCodProd;
    private javax.swing.JLabel txtColor;
    private javax.swing.JTextField txtDemanda;
    private javax.swing.JLabel txtInfoBas;
    private javax.swing.JLabel txtInfoBas1;
    private javax.swing.JLabel txtNomBa1;
    private javax.swing.JLabel txtNomBa2;
    private javax.swing.JLabel txtNomBa3;
    private javax.swing.JLabel txtValFin;
    private javax.swing.JLabel txtViscoCin;
    private javax.swing.JLabel txtViscoDin;
    private javax.swing.JLabel txtVola;
    // End of variables declaration//GEN-END:variables
}
